#!/usr/bin/env python

"""Script to 'tilize' 9 windows generated by main.py. Applicable for i3 window manager only."""
import i3

workspaces = i3.get_workspaces();

windows = [x for x in i3.filter(nodes=[]) if 'Figure' in x['name']]

for window in windows:
    window['number'] = int(window['name'].replace('Figure ', ''))

windows.sort(key=lambda x: x['number'])

print('Moving all windows to workspace 3')
for window in windows:
    i3.focus(title=window['name'])
    #i3.command('move container to workspace 4')
    i3.command('move container to workspace 3')

for window in windows:
    i3.focus(title=window['name'])
    if window['number'] %3 == 1:
        i3.command('split v')
    else:
        i3.command('move left')

print('Moving to workspace', 3)
#i3.workspace('3')
